[package]
name = "rust-indexer"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
envconfig = "0.11.0"
hex-literal = "1.0.0"
json = "0.12.4"
serde_json = "1.0.140"
tokio = "1.44.1"
web3 = "0.19.0"
